### PR TITLE
Added a text in the file

### PR DESCRIPTION
**Pull request by Ayumu000**
So I added a "**Hello World**" in the text file.

### CODE REVIEW

**Comment by Ayumu00** [comment]
Can you change the text into "Nice World" instead of "Hello World!"

**Review by Ayumu00 — COMMENTED** [review]
Can you change the text into "Nice World" instead of "Hello World!"

**Comment by Ayumu000** [comment]
Alright then.

**Comment by Ayumu000** [comment]
> Can you change the text into "Nice World" instead of "Hello World!"

Okay then

**Review by Ayumu00 — APPROVED** [review]

**Pull request merged**
